import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os

# Page Config
st.set_page_config(page_title="IPL 360° Analytics", page_icon="🏏", layout="wide")

# Title
st.title("🏏 IPL Fan Engagement & Performance Analytics")
st.markdown("**Event-Driven Analytics System** | *Fan Engagement • Team Performance • Revenue Proxies*")

# --- DATA LOADING ---
@st.cache_data
def load_data():
    base_path = "../data/processed/"
    try:
        matches = pd.read_csv(os.path.join(base_path, "matches_enriched.csv"))
        players = pd.read_csv(os.path.join(base_path, "player_stats.csv"))
        # Load sample for intensity if needed, or aggregate from full
        return matches, players
    except FileNotFoundError:
        return None, None

matches, players = load_data()

if matches is None:
    st.error("❌ Data not found! Please run the notebooks in `notebooks/` to generate processed data.")
    st.stop()

# --- SIDEBAR ---
st.sidebar.header("🎯 Navigation")
page = st.sidebar.radio("Go to", ["Team Explorer", "Player Intelligence", "Venue Insights"])

st.sidebar.markdown("---")
st.sidebar.info("Built for Sports Analytics Interview\n\n**Tech Stack:** Python, DuckDB, Streamlit, Plotly")

# --- PAGES ---

# 1. TEAM EXPLORER
if page == "Team Explorer":
    st.header("🏆 Team Engagement & Efficiency")
    
    # Metrics
    c1, c2, c3 = st.columns(3)
    c1.metric("Total Matches", matches.shape[0])
    c1.metric("Total Seasons", matches['season'].nunique())
    
    # Team Stats
    team_stats = matches.groupby('winner')['match_intensity'].mean().sort_values(ascending=False).reset_index()
    
    st.subheader("Match Intensity by Winning Team")
    fig = px.bar(team_stats, x='winner', y='match_intensity', color='match_intensity',
                 labels={'winner': 'Team', 'match_intensity': 'Avg Engagement Index'},
                 title="Which Teams Play the Most Exciting Cricket?")
    st.plotly_chart(fig, use_container_width=True)
    
    st.markdown("> **Insight:** High intensity games correlate with higher fan engagement.")

# 2. PLAYER INTELLIGENCE
elif page == "Player Intelligence":
    st.header("⚡ Star Player Impact Analysis")
    
    # Filter
    min_runs = st.slider("Minimum Runs Scored", 0, 5000, 1000)
    filtered_players = players[players['batsman_runs'] > min_runs]
    
    # Scatter: Consistency vs Strike Rate
    st.subheader("Consistency vs. Explosiveness (Moneyball Quadrant)")
    fig2 = px.scatter(filtered_players, x='consistency_index', y='strike_rate',
                      size='batsman_runs', color='runs_per_match', hover_name='batsman',
                      title="Identifying Reliable Stars vs. Hype Players")
    st.plotly_chart(fig2, use_container_width=True)
    
    st.markdown("""
    - **Top Right:** Superstars (Consistent & Fast)
    - **Bottom Right:** Anchors (Consistent but Slow)
    - **Top Left:** Hitter/Finishers (High SR, Low Consistency)
    """)

# 3. VENUE INSIGHTS
elif page == "Venue Insights":
    st.header("🏟️ Venue Advantage & Atmosphere")
    
    venue_stats = matches.groupby('venue').agg({
        'match_intensity': 'mean',
        'id': 'count'
    }).reset_index().rename(columns={'id': 'matches_hosted'})
    
    venue_stats = venue_stats[venue_stats['matches_hosted'] > 10]
    
    fig3 = px.bar(venue_stats, x='venue', y='match_intensity', color='matches_hosted',
                  title="Most Electrifying Stadiums (Avg Match Intensity)")
    st.plotly_chart(fig3, use_container_width=True)

# Footer
st.markdown("---")
st.markdown("🥈 **IPL Analytics Platform** | Generated by AI Agent")
